"""
MCU database loader module.

Loads STM32 MCU pin/peripheral data from JSON files (generated by stm32-data)
and provides query APIs for pin validation and conflict detection.

Data source: stm32-data-generated JSON files in generator/data/mcu/
"""

import json
import logging
import os
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("hw2c.mcu_db")

# Default directory for MCU JSON database files
_DEFAULT_DATA_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "data", "mcu"
)


class MCUDatabase:
    """In-memory database of MCU pin/peripheral information loaded from JSON."""

    def __init__(self, name: str, family: str, raw: dict):
        self._name = name
        self._family = family
        self._peripherals: Dict[str, dict] = {}
        self._pin_to_signals: Dict[str, List[dict]] = {}
        self._periph_to_pins: Dict[str, List[Tuple[str, str, Optional[int]]]] = {}

        self._build_index(raw)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @classmethod
    def from_json(cls, json_path: str) -> "MCUDatabase":
        """Load database from a JSON file path.

        Args:
            json_path: Path to stm32-data JSON file.

        Returns:
            MCUDatabase instance.

        Raises:
            FileNotFoundError: If json_path does not exist.
            ValueError: If JSON is malformed or missing required fields.
        """
        if not os.path.exists(json_path):
            raise FileNotFoundError(f"MCU database file not found: {json_path}")

        with open(json_path, "r", encoding="utf-8") as f:
            raw = json.load(f)

        name = raw.get("name", "Unknown")
        family = raw.get("family", "Unknown")
        logger.info("Loaded MCU database: %s (%s) from %s", name, family, json_path)
        return cls(name, family, raw)

    @classmethod
    def from_mcu_name(cls, mcu_name: str, data_dir: Optional[str] = None) -> "MCUDatabase":
        """Auto-discover and load database from MCU part number.

        Looks for <mcu_name>.json and <mcu_name_base>.json in data_dir.
        For example, 'STM32G0B1RET6' tries:
          1. STM32G0B1RET6.json
          2. STM32G0B1RE.json  (first 10 chars)

        Args:
            mcu_name: MCU part number (e.g., 'STM32G0B1RET6').
            data_dir: Directory containing JSON files (default: generator/data/mcu/).

        Returns:
            MCUDatabase instance.

        Raises:
            FileNotFoundError: If no matching JSON file found.
        """
        directory = data_dir or _DEFAULT_DATA_DIR
        # Build candidates with various truncations to match base part numbers.
        # STM32 part: STM32 + family(2) + subfamily(2) + pins(1) + flash(1) = 11
        # Full part adds package(1-2) + temperature(1) = 13-14 chars.
        # e.g. 'STM32G0B1RET6' (13) -> base 'STM32G0B1RE' (11)
        name_upper = mcu_name.upper()
        candidates = [
            f"{name_upper}.json",
            f"{name_upper[:11]}.json",  # e.g. STM32G0B1RE
            f"{name_upper[:12]}.json",  # e.g. STM32G0B1RET
            f"{name_upper[:10]}.json",  # e.g. STM32G0B1R
            f"{name_upper[:7]}.json",   # e.g. STM32G0
        ]

        for name in candidates:
            path = os.path.join(directory, name)
            if os.path.exists(path):
                return cls.from_json(path)

        tried = ", ".join(candidates)
        raise FileNotFoundError(
            f"No MCU database found for '{mcu_name}' in {directory}. "
            f"Tried: {tried}"
        )

    @property
    def name(self) -> str:
        """MCU name (e.g., 'STM32G0B1RE')."""
        return self._name

    @property
    def family(self) -> str:
        """MCU family (e.g., 'STM32G0')."""
        return self._family

    def get_pin(self, pin_name: str) -> Optional[dict]:
        """Return all signals available on a pin.

        Args:
            pin_name: Pin identifier (e.g., 'PA2').

        Returns:
            dict with 'pin' and 'signals' keys, or None if pin not found.
        """
        pin_name = pin_name.upper()
        if pin_name in self._pin_to_signals:
            return {
                "pin": pin_name,
                "signals": self._pin_to_signals[pin_name],
            }
        return None

    def get_pin_signals(self, pin_name: str) -> List[dict]:
        """Return all signal entries (with peripheral, signal, af) for a pin.

        Each entry: {'peripheral': 'USART2', 'signal': 'TX', 'af': 1}
        """
        pin_name = pin_name.upper()
        return self._pin_to_signals.get(pin_name, [])

    def get_pin_af_functions(self, pin_name: str) -> List[str]:
        """Return all AF function names for a pin (e.g., ['USART2_TX', 'I2C1_SCL']).

        Only includes functions that have an explicit AF number (non-None af).
        Analog signals (af=None) are excluded because they use a different
        configuration path (analog mode rather than alternate function).
        """
        pin_name = pin_name.upper()
        functions: List[str] = []
        for entry in self._pin_to_signals.get(pin_name, []):
            if entry.get("af") is not None:
                functions.append(f"{entry['peripheral']}_{entry['signal']}")
        return functions

    def get_peripheral_pins(self, peripheral: str) -> List[str]:
        """Return all pin names that support a given peripheral.

        Args:
            peripheral: Peripheral name (e.g., 'I2C1', 'USART2').

        Returns:
            List of pin name strings.
        """
        peripheral = peripheral.upper()
        entries = self._periph_to_pins.get(peripheral, [])
        return [pin for pin, _, _ in entries]

    def get_peripheral_signals(self, peripheral: str) -> List[dict]:
        """Return all (pin, signal, af) tuples for a peripheral.

        Each entry: {'pin': 'PA2', 'signal': 'TX', 'af': 1}
        """
        peripheral = peripheral.upper()
        return [
            {"pin": pin, "signal": sig, "af": af}
            for pin, sig, af in self._periph_to_pins.get(peripheral, [])
        ]

    def get_peripheral_info(self, peripheral: str) -> Optional[dict]:
        """Return peripheral metadata (address, interrupts, DMA channels).

        Args:
            peripheral: Peripheral name.

        Returns:
            dict or None if peripheral not found.
        """
        peripheral = peripheral.upper()
        periph = self._peripherals.get(peripheral)
        if periph is None:
            return None
        return {
            "name": periph.get("name"),
            "address": periph.get("address"),
            "interrupts": periph.get("interrupts", []),
            "dma_channels": periph.get("dma_channels", []),
        }

    def is_valid_pin(self, pin_name: str) -> bool:
        """Check whether a pin exists in this MCU.

        Args:
            pin_name: Pin identifier (e.g., 'PA2').

        Returns:
            True if pin exists.
        """
        return pin_name.upper() in self._pin_to_signals

    def resolve_pin_function(self, pin_name: str, peripheral: str, signal: str) -> Optional[int]:
        """Return the AF number for a specific (pin, peripheral, signal) combination.

        Args:
            pin_name: Pin identifier.
            peripheral: Peripheral name.
            signal: Signal name (e.g., 'TX', 'SCL').

        Returns:
            AF number (int) if the combination is valid, None otherwise.
        """
        pin_name = pin_name.upper()
        peripheral = peripheral.upper()
        signal = signal.upper()

        for entry in self._pin_to_signals.get(pin_name, []):
            if entry["peripheral"] == peripheral and entry["signal"] == signal:
                return entry.get("af")

        return None

    def list_peripherals(self) -> List[str]:
        """Return all peripheral names known to this MCU."""
        return sorted(self._peripherals.keys())

    # ------------------------------------------------------------------
    # Index building
    # ------------------------------------------------------------------

    def _build_index(self, raw: dict) -> None:
        """Build in-memory indexes from raw JSON data.

        Handles both simplified test data (top-level 'peripherals' key) and
        real stm32-data format (nested under 'cores[0].peripherals').

        Indexes built:
          - _peripherals: peripheral name -> raw peripheral dict
          - _pin_to_signals: pin name -> list of {peripheral, signal, af} entries
          - _periph_to_pins: peripheral name -> list of (pin, signal, af) tuples
        """
        # Try real stm32-data format first (cores[0].peripherals), then
        # fall back to simplified test format (top-level 'peripherals').
        cores = raw.get("cores", [])
        if cores and isinstance(cores, list) and len(cores) > 0:
            peripherals = cores[0].get("peripherals", [])
        else:
            peripherals = raw.get("peripherals", [])
        if not peripherals:
            logger.warning("No peripherals found in MCU database for %s", self._name)

        pin_seen: Dict[str, set] = {}  # pin -> set of (periph, signal)

        for periph in peripherals:
            name = periph.get("name", "").upper()
            if not name:
                continue

            self._peripherals[name] = periph

            for pin_entry in periph.get("pins", []):
                pin = pin_entry.get("pin", "").upper()
                signal = pin_entry.get("signal", "").upper()
                af = pin_entry.get("af")  # may be None for analog

                if not pin or not signal:
                    continue

                # Deduplicate: same (pin, peripheral, signal) may appear multiple times
                key = (name, signal)
                if pin not in pin_seen:
                    pin_seen[pin] = set()
                if key in pin_seen[pin]:
                    continue
                pin_seen[pin].add(key)

                # Populate pin -> signals index
                if pin not in self._pin_to_signals:
                    self._pin_to_signals[pin] = []
                self._pin_to_signals[pin].append({
                    "peripheral": name,
                    "signal": signal,
                    "af": af,
                })

                # Populate peripheral -> pins index
                if name not in self._periph_to_pins:
                    self._periph_to_pins[name] = []
                self._periph_to_pins[name].append((pin, signal, af))

        logger.debug(
            "Indexed %d peripherals, %d pins for %s",
            len(self._peripherals), len(self._pin_to_signals), self._name,
        )
