/**
 * @file    boot_main.c
 * @brief   Bootloader 主入口
 *          上电 → 读取启动标志 → CRC 校验 → 跳转 App 或 回退到备用槽位。
 *          不依赖 HAL，仅用 CMSIS 寄存器操作。
 *          Auto-generated by Hardware2Code
 */

#include "boot_nvm.h"
#include "boot_crc.h"
#include "boot_jump.h"
#include "stm32g0xx.h"

/* ========== App 槽位地址 ========== */
#define APP_A_START     0x08002000UL   /* App Slot A（Bank1，Bootloader 之后） */
#define APP_A_SIZE      0x0003E000UL   /* Slot A 总大小 = 248KB */
#define APP_B_START     0x08040000UL   /* App Slot B（Bank2） */
#define APP_B_SIZE      0x00040000UL   /* Slot B 总大小 = 256KB */

/* ========== 指示灯配置（PC0, 低电平点亮） ========== */
#define BOOT_LED_PORT   GPIOC
#define BOOT_LED_PIN    (1UL << 0)         /* GPIO 位 0 = PC0 */
#define BOOT_LED_ON()   (BOOT_LED_PORT->BRR = BOOT_LED_PIN)
#define BOOT_LED_OFF()  (BOOT_LED_PORT->BSRR = BOOT_LED_PIN)

/* ========== 简易延时（阻塞循环，约 1ms @ 16MHz HSI） ========== */
static void delay_ms(uint32_t ms)
{
    for (uint32_t i = 0; i < ms; i++) {
        for (volatile uint32_t j = 0; j < 2000; j++) { }
    }
}

/* ========== LED 错误闪烁（SOS 模式：3 短 + 3 长 + 3 短，然后长灭） ========== */
static void led_error_blink(void)
{
    const uint32_t short_ms = 200;
    const uint32_t long_ms  = 600;
    const uint32_t gap_ms   = 200;
    const uint32_t pause_ms = 2000;

    for (uint32_t cycle = 0; ; cycle++) {
        /* 3 短闪 */
        for (int i = 0; i < 3; i++) {
            BOOT_LED_ON();  delay_ms(short_ms);
            BOOT_LED_OFF(); delay_ms(gap_ms);
        }
        delay_ms(gap_ms);

        /* 3 长闪 */
        for (int i = 0; i < 3; i++) {
            BOOT_LED_ON();  delay_ms(long_ms);
            BOOT_LED_OFF(); delay_ms(gap_ms);
        }
        delay_ms(gap_ms);

        /* 3 短闪 */
        for (int i = 0; i < 3; i++) {
            BOOT_LED_ON();  delay_ms(short_ms);
            BOOT_LED_OFF(); delay_ms(gap_ms);
        }

        delay_ms(pause_ms);
    }
}

/* ========== 简易时钟初始化（HSI 16MHz，仅配置必要时钟） ========== */
static void clock_init(void)
{
    /* 使能 GPIO C 时钟（LED） */
    RCC->IOPENR |= RCC_IOPENR_GPIOCEN;
}

/* ========== GPIO 初始化（LED PC0 推挽输出） ========== */
static void gpio_init(void)
{
    BOOT_LED_PORT->MODER   = (BOOT_LED_PORT->MODER & ~(3UL << 0)) | (1UL << 0);  /* 输出模式 */
    BOOT_LED_PORT->OTYPER &= ~BOOT_LED_PIN;                                       /* 推挽 */
    BOOT_LED_PORT->OSPEEDR = (BOOT_LED_PORT->OSPEEDR & ~(3UL << 0)) | (0UL << 0); /* 低速 */
    BOOT_LED_PORT->PUPDR  &= ~(3UL << 0);                                         /* 无上下拉 */
    BOOT_LED_OFF();                                                               /* 默认灭 */
}

/* ========== 系统复位 ========== */
static void soft_reset(void)
{
    __DSB();
    SCB->AIRCR = (0x5FAUL << SCB_AIRCR_VECTKEY_Pos) | SCB_AIRCR_SYSRESETREQ_Msk;
    __DSB();
    while (1) { }
}

/* ========== 诊断 LED 闪烁（Bootloader 存活信号，3 次慢闪） ========== */
static void led_heartbeat(void)
{
    for (int i = 0; i < 3; i++) {
        BOOT_LED_ON();  delay_ms(200);
        BOOT_LED_OFF(); delay_ms(200);
    }
}

/* ========== 主入口 ========== */
int main(void)
{
    /* --- 阶段 1: 硬件初始化 --- */
    clock_init();
    gpio_init();

    /* 诊断：Bootloader 存活信号（3 次慢闪，约 1.2 秒）
       如果能看到此闪烁 → Bootloader 启动正常，问题在后续阶段
       如果看不到 → Bootloader 未执行到此处（向量表/时钟问题） */
    led_heartbeat();

    boot_nvm_init();

    /* --- 阶段 2: 读取持久化状态 --- */
    bool was_boot_ok  = boot_nvm_is_boot_ok();
    uint32_t attempt  = boot_nvm_get_attempt_count();
    uint32_t slot     = boot_nvm_get_active_slot();

    /* 检查 IWDG 复位源：如果上次复位由 IWDG 引起，说明 App 死锁，计为启动失败 */
    if (RCC->CSR & RCC_CSR_IWDGRSTF) {
        was_boot_ok = false;
    }

    /* 清除所有复位标志（为下次复位检测做准备） */
    RCC->CSR |= RCC_CSR_RMVF;

    /* --- 阶段 3: 根据上次启动结果更新计数器 --- */
    if (was_boot_ok) {
        /* 上次启动成功 → 计数归零 */
        boot_nvm_clear_attempt_count();
        attempt = 0;
    } else {
        /* 上次启动失败（或首次上电） → 计数 +1 并持久化 */
        boot_nvm_inc_attempt_count();
        attempt = boot_nvm_get_attempt_count();
    }

    /* 清除 boot_ok 标志（新一轮启动开始） */
    boot_nvm_clear_boot_ok();

    /* --- 阶段 4: 检查是否超过最大重试次数 --- */
    if (attempt > BOOT_MAX_RETRIES) {
        /* 切换到备用槽位 */
        boot_nvm_swap_active_slot();
        slot = boot_nvm_get_active_slot();
        attempt = 0;

        /* 短闪 2 次表示槽位切换 */
        for (int i = 0; i < 2; i++) {
            BOOT_LED_ON();  delay_ms(100);
            BOOT_LED_OFF(); delay_ms(100);
        }

        soft_reset();   /* 软复位，重入 Bootloader */
    }

    /* --- 阶段 4.5: FOTA 补丁检测 ---
     * 检查 TAMP BKP4R 中是否标记了待应用的固件更新。
     * 若 Slot B 中有通过 FOTA 写⼊的新固件且版本号更高，自动切换。 */
    #define FOTA_FLAG_PATCH_READY   0x02U

    /* 使能 RTC/TAMP 时钟以读取备份寄存器 */
    RCC->APBENR1 |= RCC_APBENR1_RTCAPBEN;
    (void)RCC->APBENR1;  /* 等待总线同步 */

    uint32_t fota_flags = TAMP->BKP4R;
    if (fota_flags & FOTA_FLAG_PATCH_READY) {
        /* Slot B 中有通过 FOTA 写入的新固件 */
        uint32_t current_ver = boot_read_fw_version(
            (slot == BOOT_SLOT_A) ? APP_A_START : APP_B_START);
        uint32_t new_ver = boot_read_fw_version(APP_B_START);

        if (new_ver > 0 && new_ver > current_ver) {
            /* 校验 Slot B 中的新固件 */
            if (boot_crc_verify(APP_B_START, APP_B_SIZE)) {
                /* 新固件有效，切换到 Slot B */
                if (slot != BOOT_SLOT_B) {
                    boot_nvm_swap_active_slot();
                    slot = BOOT_SLOT_B;
                }
                /* 快速闪烁 3 次: FOTA 升级成功 */
                for (int i = 0; i < 3; i++) {
                    BOOT_LED_ON();  delay_ms(50);
                    BOOT_LED_OFF(); delay_ms(50);
                }
            }
        }
        /* 清除 FOTA 标志 */
        TAMP->BKP4R = 0;
    }

    /* --- 阶段 5: 校验当前槽位固件 --- */
    uint32_t app_addr;
    uint32_t app_size;

    if (slot == BOOT_SLOT_A) {
        app_addr = APP_A_START;
        app_size = APP_A_SIZE;
    } else {
        app_addr = APP_B_START;
        app_size = APP_B_SIZE;
    }

    bool crc_ok = boot_crc_verify(app_addr, app_size);

    /* --- 阶段 6: 启动 App 或进入恢复模式 --- */
    if (crc_ok) {
        /* 固件完整 — 长闪 LED 1 次表示即将跳转 */
        BOOT_LED_ON();  delay_ms(300);
        BOOT_LED_OFF(); delay_ms(300);

        /* 跳转 App */
        boot_jump_to_app(app_addr);
        /* 跳转失败不应到达此处 */
    }

    /* 固件校验失败 */
    /* CRC 损坏说明固件写入不完整或 Flash 故障，直接切换槽位 */
    boot_nvm_swap_active_slot();

    /* 如果两个槽位都已尝试过且仍失败 → Recovery */
    if ((slot == BOOT_SLOT_A && boot_nvm_get_active_slot() == BOOT_SLOT_A) ||
        (slot == BOOT_SLOT_B && boot_nvm_get_active_slot() == BOOT_SLOT_B)) {
        /* 已经切换过一次又回到原来的槽位 → 两个槽位都有问题 */
        led_error_blink();  /* SOS 信号，死循环 */
    }

    /* 切换后软复位，尝试另一个槽位 */
    soft_reset();
}